#ifndef WHITESPACE_H
#define WHITESPACE_H

// https://esolangs.org/wiki/Whitespace

#include <stdbool.h>

#ifndef _CRT_SECURE_NO_WARNINGS // fopen_s
#define _CRT_SECURE_NO_WARNINGS
#endif // _CRT_SECURE_NO_WARNINGS

#ifdef WHITESPACE_DEBUG
#define WHITESPACE_S 'S'
#define WHITESPACE_T 'T'
#define WHITESPACE_L 'L'
#else // not WHITESPACE_DEBUG
#define WHITESPACE_S ' '
#define WHITESPACE_T '\t'
#define WHITESPACE_L '\n'
#endif // not WHITESPACE_DEBUG

// clang-format off
#define WHITESPACE_IO_READ_ASCII            WHITESPACE_T, WHITESPACE_L,   WHITESPACE_T, WHITESPACE_S
#define WHITESPACE_IO_READ_NUMBER           WHITESPACE_T, WHITESPACE_L,   WHITESPACE_T, WHITESPACE_T
#define WHITESPACE_IO_OUTPUT_ASCII          WHITESPACE_T, WHITESPACE_L,   WHITESPACE_S, WHITESPACE_S
#define WHITESPACE_IO_OUTPUT_NUMBER         WHITESPACE_T, WHITESPACE_L,   WHITESPACE_S, WHITESPACE_T
#define WHITESPACE_STACK_PUSH               WHITESPACE_S,                 WHITESPACE_S
#define WHITESPACE_STACK_DUP                WHITESPACE_S,                 WHITESPACE_L, WHITESPACE_S
#define WHITESPACE_STACK_SWAP               WHITESPACE_S,                 WHITESPACE_L, WHITESPACE_T
#define WHITESPACE_STACK_DISCARD            WHITESPACE_S,                 WHITESPACE_L, WHITESPACE_L
#define WHITESPACE_STACK_COPY_NTH           WHITESPACE_S,                 WHITESPACE_T, WHITESPACE_S
#define WHITESPACE_STACK_SLIDE_N            WHITESPACE_S,                 WHITESPACE_T, WHITESPACE_L
#define WHITESPACE_ARITH_ADD                WHITESPACE_T, WHITESPACE_S,   WHITESPACE_S, WHITESPACE_S
#define WHITESPACE_ARITH_SUB                WHITESPACE_T, WHITESPACE_S,   WHITESPACE_S, WHITESPACE_T
#define WHITESPACE_ARITH_MUL                WHITESPACE_T, WHITESPACE_S,   WHITESPACE_S, WHITESPACE_L
#define WHITESPACE_ARITH_DIV                WHITESPACE_T, WHITESPACE_S,   WHITESPACE_T, WHITESPACE_S
#define WHITESPACE_ARITH_MOD                WHITESPACE_T, WHITESPACE_S,   WHITESPACE_T, WHITESPACE_T
#define WHITESPACE_FLOW_LABEL_CREATE        WHITESPACE_L, WHITESPACE_S,   WHITESPACE_S
#define WHITESPACE_FLOW_SUBROUTINE_CALL     WHITESPACE_L, WHITESPACE_S,   WHITESPACE_T
#define WHITESPACE_FLOW_LABEL_JUMP          WHITESPACE_L, WHITESPACE_S,   WHITESPACE_L
#define WHITESPACE_FLOW_LABEL_JUMP_IF0      WHITESPACE_L,                 WHITESPACE_T, WHITESPACE_S
#define WHITESPACE_FLOW_LABEL_JUMP_NEG      WHITESPACE_L,                 WHITESPACE_T, WHITESPACE_T
#define WHITESPACE_FLOW_SUBROUTINE_RETURN   WHITESPACE_L,                 WHITESPACE_T, WHITESPACE_L
#define WHITESPACE_FLOW_EXIT                WHITESPACE_L,                 WHITESPACE_L, WHITESPACE_L
#define WHITESPACE_HEAP_STORE               WHITESPACE_T, WHITESPACE_T,   WHITESPACE_S
#define WHITESPACE_HEAP_LOAD                WHITESPACE_T, WHITESPACE_T,   WHITESPACE_T
// clang-format on

bool WhiteSpace_Intepret(const char *code);

#endif // WHITESPACE_H
