#ifndef WHITESPACE_H
#define WHITESPACE_H

// https://esolangs.org/wiki/Whitespace

#include <stdbool.h>

#ifndef _CRT_SECURE_NO_WARNINGS // fopen_s
#define _CRT_SECURE_NO_WARNINGS
#endif // _CRT_SECURE_NO_WARNINGS

#ifdef WHITESPACE_DEBUG
#define WHITESPACE_S 'S'
#define WHITESPACE_T 'T'
#define WHITESPACE_L 'L'
#else // not WHITESPACE_DEBUG
#define WHITESPACE_S ' '
#define WHITESPACE_T '\t'
#define WHITESPACE_L '\n'
#endif // not WHITESPACE_DEBUG

#define WHITESPACE_IO_READ_ASCII T, L, T, S
#define WHITESPACE_IO_READ_NUMBER T, L, T, T
#define WHITESPACE_IO_OUTPUT_ASCII T, L, S, S
#define WHITESPACE_IO_OUTPUT_NUMBER T, L, S, T
#define WHITESPACE_STACK_PUSH S, S
#define WHITESPACE_STACK_DUP S, L, S
#define WHITESPACE_STACK_SWAP S, L, T
#define WHITESPACE_STACK_DISCARD S, L, L
#define WHITESPACE_STACK_COPY_NTH S, T, S
#define WHITESPACE_STACK_SLIDE_N S, T, L
#define WHITESPACE_ARTH_ADD T, S, S, S
#define WHITESPACE_ARTH_SUB T, S, S, T
#define WHITESPACE_ARTH_MUL T, S, S, L
#define WHITESPACE_ARTH_DIV T, S, T, S
#define WHITESPACE_ARTH_MOD T, S, T, T
#define WHITESPACE_FLOW_LABEL_CREATE L, S, S
#define WHITESPACE_FLOW_SUBROUTINE_CALL L, S, T
#define WHITESPACE_FLOW_LABEL_JUMP L, S, L
#define WHITESPACE_FLOW_LABEL_JUMP_IF0 L, T, S
#define WHITESPACE_FLOW_LABEL_JUMP_NEG L, T, T
#define WHITESPACE_FLOW_SUBROUTINE_RETURN L, T, L
#define WHITESPACE_FLOW_EXIT L, L, L
#define WHITESPACE_HEAP_STORE T, T, S
#define WHITESPACE_HEAP_LOAD T, T, T

bool WhiteSpace_Intepret(const char *code);

#endif // WHITESPACE_H
